fuel_api:
  url: "http://localhost:8000"

tests:
    config_directory: clusters
    test_simple:
        cluster: simple
        test: oscf

deploy_timeout: 3600
discovery_timeout: 600
name: "sert-cluster"

report:
  mail:
    smtp_server: "smtp.gmail.com"
    mail_to: "lht-sert-results@mirantis.com"
    mail_from: "lht-sert-results@mirantis.com"
    login: "lht-sert-results@mirantis.com"
