NODES_NUMBER: 2
RELEASE: 1
DEPLOYMENT_MODE: "ha_compact"
NUM_CONTROLLERS: 1
NUM_COMPUTES: 1
NUM_STORAGES: 0
DEPLOY_TIMEOUT: 600
NODES_DISCOVERY_TIMEOUT: 600
TESTRUN_TIMEOUT: 3600
NET_PROVIDER: "nova_network"
NAME: "foo001"