NODES_NUMBER: 10
RELEASE: 1
DEPLOYMENT_MODE: "ha_compact"
NUM_CONTROLLERS: 2
NUM_COMPUTES: 6
NUM_STORAGES: 2
DEPLOY_TIMEOUT: 3600
NODES_DISCOVERY_TIMEOUT: 600
TESTRUN_TIMEOUT: 3600
NET_PROVIDER: "nova_network"
NAME: "sert-cluster"